import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Links } from "./components/Links";

let counter = 0;

type Payload = {
  message: string;
};

export default function Home({ message }: Payload) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Links />
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>

        <p className={styles.description}>{message}</p>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const message = await new Promise((resolve) => {
    setTimeout(() => {
      resolve(`This is some slow data reloading for the ${++counter} time`);
    }, 8000); // Simulate a slow API call
  });

  return {
    props: {
      message,
    },
    revalidate: 60, // In seconds
  };
}
